# -*- coding: utf-8 -*-
"""summarization with BART .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nq8GGd0W34v0ZUOGJaBnUIgfUcymZV-Z
"""

# Install necessary libraries
!pip install transformers tqdm

# Import required modules
import pandas as pd
from transformers import BartTokenizer, BartForConditionalGeneration
import torch
from tqdm import tqdm
from google.colab import files

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/DTSC 5082 Datasets/cleaned_discharge.csv")
text_column = "text"  # Replace with your actual column name
df = df.dropna(subset=[text_column]).head(1000)  # Limit to first 2000 non-null entries

# Set device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Load BART model and tokenizer
model_name = "facebook/bart-large"
tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name).to(device)

# Detect text column
text_column = next((col for col in ['text', 'abstract', 'report_text', 'clinical_summary', 'discharge_note'] if col in df.columns), None)

if not text_column:
    raise ValueError(f"❌ No valid text column found. Columns available: {df.columns.tolist()}")

print(f"✅ Using column: '{text_column}' for summarization...")

# Define summarization function
def summarize_text(text, max_length=200):
    if pd.isna(text) or text.strip() == "":
        return "No text available for summarization."
    inputs = tokenizer(text, return_tensors="pt", max_length=1024, truncation=True).to(device)
    summary_ids = model.generate(
        inputs["input_ids"],
        max_length=max_length,
        num_beams=4,
        length_penalty=2.0,
        early_stopping=True
    )
    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

for i in range(10):
    print(f"\n======================= ENTRY {i + 1} =======================")

    original_text = df[text_column].iloc[i]
    print("\n🔹 Original Text:\n", original_text[:1000], "...")  # Show only first 1000 chars for brevity

    summary = summarize_text(original_text)
    print("\n🔸 Summary:\n", summary)

# Apply summarization with progress bar
tqdm.pandas()
df['summary'] = df[text_column].progress_apply(summarize_text)

from google.colab import files
df.to_csv("summarized_1000_clinical_data.csv", index=False)
files.download("summarized_1000_clinical_data.csv")

# Preview a few rows
print(df[['text', 'summary']].head(5))

!apt-get install git

!git config --global user.email "your_email@example.com"
!git config --global user.name "Your Name"